#include <stdlib.h>
#include <unistd.h>

#include "capstone/include/capstone/capstone.h"

int main(int argc, char** argv) {
    // The buffer we will pass to the library
    uint8_t buf[128];

    ssize_t read_bytes = read(stdin, buf, 128);

    csh handle;
    cs_insn *insn;

    size_t count;

    // cs_open and cs_disasm are the main functions needed to use capstone.
    // we feed them the data generated by AFL.
    // a normal program using capstone would then use the output of cs_disasm
    // to print a disassembly to the user for example
    if (cs_open(CS_ARCH_X86, CS_MODE_64, &handle) == CS_ERR_OK) {
        count = cs_disasm(handle, buf, read_bytes, 0x1000, 0, &insn);

        // don't forget to clean up after ourselves
        cs_free(insn, count);
    } else {
        return -1;
    }
    // close the capstone library
    cs_close(&handle);
}
